/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mdplp_kelompok_p7;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Norma Syafitri
 */
public class ITWorkerForm extends javax.swing.JFrame {
    
    DefaultTableModel model;
    String tabel_klik="";

    /**
     * Creates new form ITWokerForm
     */
    public ITWorkerForm() {
        initComponents();
        model = (DefaultTableModel) jTable1.getModel();
        jTable1.setModel(model);
        this.loadDataToTable();
    }
    
 public void loadDataToTable()
    {
        DefaultTableModel dm = (DefaultTableModel)jTable1.getModel();
        while(dm.getRowCount() > 0)
        {
            dm.removeRow(0);
        }
        
        try {
            Connection conn = KoneksiDB.getKoneksi();
            Statement s = conn.createStatement();
            
            String query = "SELECT * FROM tabel_pegawai_5200411474";
            ResultSet result = s.executeQuery(query);
            
            while (result.next()) {
                Object [] obj = new Object[5];
                obj[0]= result.getString("nama_pegawai");
                obj[1]= result.getString("no_pegawai");
                obj[2]= result.getString("posisi_pegawai");
                obj[3]= result.getString("gaji_pegawai");
                obj[4]= result.getInt("id_pegawai");
                
                
                model.addRow(obj);
                
            } 
            result.close();
            s.close();
        } 
        catch (SQLException e) 
        {
            System.out.println(e.getMessage());
        }
        finally
        {
            tabel_klik="";
            
            jTable1.getColumnModel().getColumn(4).setMinWidth(0);
            jTable1.getColumnModel().getColumn(4).setMaxWidth(0);
        }
    }

 
    public void insertDataPegawai() throws NoPegawaiHarusAngka, NoPegawaiHarusPositif, NoPegawaiHarus10Digit
    {
       
        long nopegawai;
        try 
        {
            nopegawai = Long.parseLong(txtNoPegawai.getText());
        } 
        catch (NumberFormatException e) 
        {
            throw new NoPegawaiHarusAngka();
        }
        
        if (nopegawai < 0)
        {
            throw new NoPegawaiHarusPositif();
        }
        if (txtNoPegawai.getText().length() < 10 )
       {
           throw new NoPegawaiHarus10Digit();
       }
        if (txtNoPegawai.getText().length() > 10 )
       {
           throw new NoPegawaiHarus10Digit();
       }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bttnExit = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtNoPegawai = new javax.swing.JTextField();
        txtgaji = new javax.swing.JTextField();
        cmbPosisi = new javax.swing.JComboBox<>();
        bttnInsert = new javax.swing.JButton();
        bttnUpdate = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bttnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bttnExit.setBackground(new java.awt.Color(204, 0, 0));
        bttnExit.setText("Exit");
        bttnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttnExitMouseClicked(evt);
            }
        });

        jLabel1.setText("Nama");

        jLabel2.setText("No. Pegawai");

        jLabel3.setText("Posisi");

        jLabel4.setText("Gaji (IDR)");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel5.setText("IT Worker Form");

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        txtgaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgajiActionPerformed(evt);
            }
        });

        cmbPosisi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Senior Programmer", "Bussiness Analyst", "Data Center Officer", "Junior Programmer" }));
        cmbPosisi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPosisiItemStateChanged(evt);
            }
        });
        cmbPosisi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbPosisiMouseClicked(evt);
            }
        });
        cmbPosisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPosisiActionPerformed(evt);
            }
        });

        bttnInsert.setBackground(new java.awt.Color(51, 255, 102));
        bttnInsert.setText("Insert");
        bttnInsert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttnInsertMouseClicked(evt);
            }
        });

        bttnUpdate.setBackground(new java.awt.Color(0, 153, 255));
        bttnUpdate.setText("Update");
        bttnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttnUpdateMouseClicked(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "nama_pegawai", "no_pegawai", "posisi_pegawai", "gaji_pegawai", "id_pegawai"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        bttnDelete.setBackground(new java.awt.Color(255, 255, 0));
        bttnDelete.setText("Delete");
        bttnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bttnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bttnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(bttnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNama)
                            .addComponent(txtNoPegawai)
                            .addComponent(cmbPosisi, javax.swing.GroupLayout.Alignment.TRAILING, 0, 516, Short.MAX_VALUE)
                            .addComponent(txtgaji))
                        .addContainerGap(362, Short.MAX_VALUE))
                    .addComponent(jSeparator2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1005, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bttnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(bttnExit))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNoPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbPosisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtgaji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttnInsert)
                    .addComponent(bttnUpdate))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(bttnDelete)
                .addGap(72, 72, 72))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void txtgajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgajiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgajiActionPerformed

    private void cmbPosisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPosisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPosisiActionPerformed

    private void bttnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnDeleteActionPerformed
        // TODO add your handling code here:
         if (!tabel_klik.equals("")){
            try
            {
                Connection conn = KoneksiDB.getKoneksi();

                String query = "DELETE FROM tabel_pegawai_5200411474 "+"WHERE id_pegawai=?";

                PreparedStatement p = conn.prepareStatement(query);

                p.setString(1, tabel_klik);

                int rowsDeleted = p.executeUpdate();
                if (rowsDeleted > 0){
                    JOptionPane.showMessageDialog(this, "Proses Delete berhasil", "Success", JOptionPane.INFORMATION_MESSAGE );
                }
                p.close();
            }
            catch (SQLException e)
            {
                JOptionPane.showMessageDialog(this, "Proses delete gagal...", "Error", JOptionPane.ERROR_MESSAGE);
            }
            finally
            {
                this.loadDataToTable();
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Anda belum memilih data pegawai yang akan dihapus", "Error", JOptionPane.ERROR_MESSAGE);
        }
    
    }//GEN-LAST:event_bttnDeleteActionPerformed

    private void bttnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttnExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bttnExitMouseClicked

    private void bttnInsertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttnInsertMouseClicked
        // TODO add your handling code here:
        try
        {
            this.insertDataPegawai();
        }
        catch (NoPegawaiHarusAngka e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        catch (NoPegawaiHarusPositif e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        catch (NoPegawaiHarus10Digit e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }

        try
        {
            Connection conn = KoneksiDB.getKoneksi();

            String query = "INSERT INTO tabel_pegawai_5200411474 "+
            "(nama_pegawai,no_pegawai,posisi_pegawai,gaji_pegawai) "+
            "VALUES(?,?,?,?)";

            PreparedStatement p = conn.prepareStatement(query);

            p.setString(1, txtNama.getText());
            p.setString(2, txtNoPegawai.getText());
            p.setString(3, cmbPosisi.getSelectedItem().toString());
            p.setString(4, txtgaji.getText());

            int rowsInserted = p.executeUpdate();
            if (rowsInserted > 0)
            {
                JOptionPane.showMessageDialog(this, "Data berhasil disimpan", "Success", JOptionPane.INFORMATION_MESSAGE );
            }
            p.close();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Data gagal disimpan", "Error", JOptionPane.ERROR_MESSAGE);
        }
        finally
        {
            this.loadDataToTable();
        }
    }//GEN-LAST:event_bttnInsertMouseClicked

    private void bttnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttnUpdateMouseClicked
        // TODO add your handling code here:
        try
        {
            Connection conn = KoneksiDB.getKoneksi();

            String query = "UPDATE tabel_pegawai_5200411474 "+"SET nama_pegawai=?, no_pegawai=?, posisi_pegawai=?, gaji_pegawai=?"
            +"WHERE id_pegawai=?";

            PreparedStatement p = conn.prepareStatement(query);

            p.setString(1, txtNama.getText());
            p.setString(2, txtNoPegawai.getText());
            p.setString(3, cmbPosisi.getSelectedItem().toString());
            p.setString(4, txtgaji.getText());
            p.setString(5, tabel_klik);

            int rowsUpdate = p.executeUpdate();
            if (rowsUpdate > 0){
                JOptionPane.showMessageDialog(this, "Update berhasil disimpan", "Success", JOptionPane.INFORMATION_MESSAGE );
            }
            p.close();
        }
        catch (SQLException e)
        {
            JOptionPane.showMessageDialog(this, "Proses update gagal...", "Error", JOptionPane.ERROR_MESSAGE);
        }
        finally
        {
            this.loadDataToTable();
        }
    }//GEN-LAST:event_bttnUpdateMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row =jTable1.getSelectedRow();
        tabel_klik=(jTable1.getModel().getValueAt(row, 4).toString());

        txtNama.setText(jTable1.getModel().getValueAt(row, 0).toString());
        txtNoPegawai.setText(jTable1.getModel().getValueAt(row, 1).toString());

        cmbPosisi.setSelectedItem(jTable1.getModel().getValueAt(row, 2).toString());

        txtgaji.setText(jTable1.getModel().getValueAt(row, 3).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void cmbPosisiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbPosisiMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbPosisiMouseClicked

    private void cmbPosisiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPosisiItemStateChanged
        // TODO add your handling code here:
        if (cmbPosisi.getSelectedItem() == "Senior Programmer") {
            txtgaji.setText("15.000.000");
        }else if (cmbPosisi.getSelectedItem() == "Bussines Analyst") {
            txtgaji.setText("21.000.000");    
        }else if (cmbPosisi.getSelectedItem() == "Data Center Officer") {
            txtgaji.setText("18.000.000");
        }else if (cmbPosisi.getSelectedItem() == "Junior Programmer") {
            txtgaji.setText("8.000.000");
        }else{
            txtgaji.setText("21.000.000");
        }
    }//GEN-LAST:event_cmbPosisiItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ITWorkerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ITWorkerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ITWorkerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ITWorkerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ITWorkerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnDelete;
    private javax.swing.JButton bttnExit;
    private javax.swing.JButton bttnInsert;
    private javax.swing.JButton bttnUpdate;
    private javax.swing.JComboBox<String> cmbPosisi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNoPegawai;
    private javax.swing.JTextField txtgaji;
    // End of variables declaration//GEN-END:variables
}
